name: Deploy GitBook
on:
  push:
    branches:
      - main  # 确保这里是您的默认分支名称
    paths:
      - 'docs/**'
      - 'book.json'
      - 'SUMMARY.md'
      - '.github/workflows/gitbook.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.12'  # 使用较低版本的 Node.js

      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook -v
          
      - name: Fix graceful-fs issue
        run: |
          cd /opt/hostedtoolcache/node/12.22.12/x64/lib/node_modules/gitbook-cli/node_modules/npm/node_modules/
          npm install graceful-fs@4.2.0 --save

      - name: Check directory structure
        run: |
          pwd
          ls -la
          
      - name: Install dependencies
        run: |
          gitbook install
          
      - name: Check book.json and SUMMARY.md
        run: |
          cat book.json
          echo "---"
          cat SUMMARY.md

      - name: Build GitBook
        run: |
          gitbook build
          ls -la _book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          force_orphan: true
          commit_message: 'docs: update gitbook documentation'
          
      - name: Output deployment info
        run: |
          echo "Deployment completed"
          echo "Please check https://<username>.github.io/Telegram-Docs" 